// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CIDRRulePatchRequestKind.
const (
	CIDRRulePatchRequestKindCidr  CIDRRulePatchRequestKind = "cidr"
	CIDRRulePatchRequestKindGeoip CIDRRulePatchRequestKind = "geoip"
)

// Valid indicates whether the value is a known member of the CIDRRulePatchRequestKind enum.
func (e CIDRRulePatchRequestKind) Valid() bool {
	switch e {
	case CIDRRulePatchRequestKindCidr:
		return true
	case CIDRRulePatchRequestKindGeoip:
		return true
	default:
		return false
	}
}

// Defines values for CompatibilityCheckComponent.
const (
	CompatibilityCheckComponentBridge  CompatibilityCheckComponent = "bridge"
	CompatibilityCheckComponentCidr    CompatibilityCheckComponent = "cidr"
	CompatibilityCheckComponentDomains CompatibilityCheckComponent = "domains"
	CompatibilityCheckComponentGeodata CompatibilityCheckComponent = "geodata"
	CompatibilityCheckComponentHrneo   CompatibilityCheckComponent = "hrneo"
)

// Valid indicates whether the value is a known member of the CompatibilityCheckComponent enum.
func (e CompatibilityCheckComponent) Valid() bool {
	switch e {
	case CompatibilityCheckComponentBridge:
		return true
	case CompatibilityCheckComponentCidr:
		return true
	case CompatibilityCheckComponentDomains:
		return true
	case CompatibilityCheckComponentGeodata:
		return true
	case CompatibilityCheckComponentHrneo:
		return true
	default:
		return false
	}
}

// Defines values for CompatibilityCheckSeverity.
const (
	CompatibilityCheckSeverityError   CompatibilityCheckSeverity = "error"
	CompatibilityCheckSeverityOk      CompatibilityCheckSeverity = "ok"
	CompatibilityCheckSeverityWarning CompatibilityCheckSeverity = "warning"
)

// Valid indicates whether the value is a known member of the CompatibilityCheckSeverity enum.
func (e CompatibilityCheckSeverity) Valid() bool {
	switch e {
	case CompatibilityCheckSeverityError:
		return true
	case CompatibilityCheckSeverityOk:
		return true
	case CompatibilityCheckSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for ConfigFileResponseName.
const (
	ConfigFileResponseNameCidr    ConfigFileResponseName = "cidr"
	ConfigFileResponseNameDomains ConfigFileResponseName = "domains"
	ConfigFileResponseNameHrneo   ConfigFileResponseName = "hrneo"
)

// Valid indicates whether the value is a known member of the ConfigFileResponseName enum.
func (e ConfigFileResponseName) Valid() bool {
	switch e {
	case ConfigFileResponseNameCidr:
		return true
	case ConfigFileResponseNameDomains:
		return true
	case ConfigFileResponseNameHrneo:
		return true
	default:
		return false
	}
}

// Defines values for ConfigFileResponseRequiredAction.
const (
	ConfigFileResponseRequiredActionNone    ConfigFileResponseRequiredAction = "none"
	ConfigFileResponseRequiredActionReload  ConfigFileResponseRequiredAction = "reload"
	ConfigFileResponseRequiredActionRestart ConfigFileResponseRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the ConfigFileResponseRequiredAction enum.
func (e ConfigFileResponseRequiredAction) Valid() bool {
	switch e {
	case ConfigFileResponseRequiredActionNone:
		return true
	case ConfigFileResponseRequiredActionReload:
		return true
	case ConfigFileResponseRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for DoctorCheckSeverity.
const (
	DoctorCheckSeverityError   DoctorCheckSeverity = "error"
	DoctorCheckSeverityOk      DoctorCheckSeverity = "ok"
	DoctorCheckSeverityWarning DoctorCheckSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DoctorCheckSeverity enum.
func (e DoctorCheckSeverity) Valid() bool {
	switch e {
	case DoctorCheckSeverityError:
		return true
	case DoctorCheckSeverityOk:
		return true
	case DoctorCheckSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for DomainDiagnosticCandidateMatchType.
const (
	DomainDiagnosticCandidateMatchTypeExact  DomainDiagnosticCandidateMatchType = "exact"
	DomainDiagnosticCandidateMatchTypeSuffix DomainDiagnosticCandidateMatchType = "suffix"
)

// Valid indicates whether the value is a known member of the DomainDiagnosticCandidateMatchType enum.
func (e DomainDiagnosticCandidateMatchType) Valid() bool {
	switch e {
	case DomainDiagnosticCandidateMatchTypeExact:
		return true
	case DomainDiagnosticCandidateMatchTypeSuffix:
		return true
	default:
		return false
	}
}

// Defines values for DomainDiagnosticResponseMatchType.
const (
	DomainDiagnosticResponseMatchTypeExact  DomainDiagnosticResponseMatchType = "exact"
	DomainDiagnosticResponseMatchTypeSuffix DomainDiagnosticResponseMatchType = "suffix"
)

// Valid indicates whether the value is a known member of the DomainDiagnosticResponseMatchType enum.
func (e DomainDiagnosticResponseMatchType) Valid() bool {
	switch e {
	case DomainDiagnosticResponseMatchTypeExact:
		return true
	case DomainDiagnosticResponseMatchTypeSuffix:
		return true
	default:
		return false
	}
}

// Defines values for DomainRulePatchRequestKind.
const (
	DomainRulePatchRequestKindDomain  DomainRulePatchRequestKind = "domain"
	DomainRulePatchRequestKindGeosite DomainRulePatchRequestKind = "geosite"
)

// Valid indicates whether the value is a known member of the DomainRulePatchRequestKind enum.
func (e DomainRulePatchRequestKind) Valid() bool {
	switch e {
	case DomainRulePatchRequestKindDomain:
		return true
	case DomainRulePatchRequestKindGeosite:
		return true
	default:
		return false
	}
}

// Defines values for DomainTargetType.
const (
	DomainTargetTypeInterface DomainTargetType = "interface"
	DomainTargetTypePolicy    DomainTargetType = "policy"
	DomainTargetTypeUnknown   DomainTargetType = "unknown"
)

// Valid indicates whether the value is a known member of the DomainTargetType enum.
func (e DomainTargetType) Valid() bool {
	switch e {
	case DomainTargetTypeInterface:
		return true
	case DomainTargetTypePolicy:
		return true
	case DomainTargetTypeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GeoDataKind.
const (
	GeoDataKindGeoip   GeoDataKind = "geoip"
	GeoDataKindGeosite GeoDataKind = "geosite"
)

// Valid indicates whether the value is a known member of the GeoDataKind enum.
func (e GeoDataKind) Valid() bool {
	switch e {
	case GeoDataKindGeoip:
		return true
	case GeoDataKindGeosite:
		return true
	default:
		return false
	}
}

// Defines values for HRNeoConfigLog.
const (
	Console HRNeoConfigLog = "console"
	File    HRNeoConfigLog = "file"
	Off     HRNeoConfigLog = "off"
	Syslog  HRNeoConfigLog = "syslog"
)

// Valid indicates whether the value is a known member of the HRNeoConfigLog enum.
func (e HRNeoConfigLog) Valid() bool {
	switch e {
	case Console:
		return true
	case File:
		return true
	case Off:
		return true
	case Syslog:
		return true
	default:
		return false
	}
}

// Defines values for HRNeoDefaultConfigResponseRequiredAction.
const (
	HRNeoDefaultConfigResponseRequiredActionRestart HRNeoDefaultConfigResponseRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the HRNeoDefaultConfigResponseRequiredAction enum.
func (e HRNeoDefaultConfigResponseRequiredAction) Valid() bool {
	switch e {
	case HRNeoDefaultConfigResponseRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for HRNeoParamMetadataRequiredAction.
const (
	HRNeoParamMetadataRequiredActionRestart HRNeoParamMetadataRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the HRNeoParamMetadataRequiredAction enum.
func (e HRNeoParamMetadataRequiredAction) Valid() bool {
	switch e {
	case HRNeoParamMetadataRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for HRNeoParamMetadataValueType.
const (
	HRNeoParamMetadataValueTypeBool        HRNeoParamMetadataValueType = "bool"
	HRNeoParamMetadataValueTypeInt         HRNeoParamMetadataValueType = "int"
	HRNeoParamMetadataValueTypePath        HRNeoParamMetadataValueType = "path"
	HRNeoParamMetadataValueTypePolicyOrder HRNeoParamMetadataValueType = "policyOrder"
	HRNeoParamMetadataValueTypePositiveInt HRNeoParamMetadataValueType = "positiveInt"
	HRNeoParamMetadataValueTypeRepeatPath  HRNeoParamMetadataValueType = "repeatPath"
	HRNeoParamMetadataValueTypeString      HRNeoParamMetadataValueType = "string"
)

// Valid indicates whether the value is a known member of the HRNeoParamMetadataValueType enum.
func (e HRNeoParamMetadataValueType) Valid() bool {
	switch e {
	case HRNeoParamMetadataValueTypeBool:
		return true
	case HRNeoParamMetadataValueTypeInt:
		return true
	case HRNeoParamMetadataValueTypePath:
		return true
	case HRNeoParamMetadataValueTypePolicyOrder:
		return true
	case HRNeoParamMetadataValueTypePositiveInt:
		return true
	case HRNeoParamMetadataValueTypeRepeatPath:
		return true
	case HRNeoParamMetadataValueTypeString:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	HydraBridge HealthResponseService = "HydraBridge"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case HydraBridge:
		return true
	default:
		return false
	}
}

// Defines values for IPDiagnosticRuntimeEvidenceFamily.
const (
	Ipv4 IPDiagnosticRuntimeEvidenceFamily = "ipv4"
	Ipv6 IPDiagnosticRuntimeEvidenceFamily = "ipv6"
)

// Valid indicates whether the value is a known member of the IPDiagnosticRuntimeEvidenceFamily enum.
func (e IPDiagnosticRuntimeEvidenceFamily) Valid() bool {
	switch e {
	case Ipv4:
		return true
	case Ipv6:
		return true
	default:
		return false
	}
}

// Defines values for ImportCSVApplyResponseRequiredAction.
const (
	ImportCSVApplyResponseRequiredActionRestart ImportCSVApplyResponseRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the ImportCSVApplyResponseRequiredAction enum.
func (e ImportCSVApplyResponseRequiredAction) Valid() bool {
	switch e {
	case ImportCSVApplyResponseRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for ImportTextRequestSection.
const (
	ImportTextRequestSectionCidr   ImportTextRequestSection = "cidr"
	ImportTextRequestSectionDomain ImportTextRequestSection = "domain"
)

// Valid indicates whether the value is a known member of the ImportTextRequestSection enum.
func (e ImportTextRequestSection) Valid() bool {
	switch e {
	case ImportTextRequestSectionCidr:
		return true
	case ImportTextRequestSectionDomain:
		return true
	default:
		return false
	}
}

// Defines values for InterfaceInfoState.
const (
	InterfaceInfoStateDown    InterfaceInfoState = "down"
	InterfaceInfoStateUnknown InterfaceInfoState = "unknown"
	InterfaceInfoStateUp      InterfaceInfoState = "up"
)

// Valid indicates whether the value is a known member of the InterfaceInfoState enum.
func (e InterfaceInfoState) Valid() bool {
	switch e {
	case InterfaceInfoStateDown:
		return true
	case InterfaceInfoStateUnknown:
		return true
	case InterfaceInfoStateUp:
		return true
	default:
		return false
	}
}

// Defines values for PutConfigResponseRequiredAction.
const (
	PutConfigResponseRequiredActionNone    PutConfigResponseRequiredAction = "none"
	PutConfigResponseRequiredActionReload  PutConfigResponseRequiredAction = "reload"
	PutConfigResponseRequiredActionRestart PutConfigResponseRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the PutConfigResponseRequiredAction enum.
func (e PutConfigResponseRequiredAction) Valid() bool {
	switch e {
	case PutConfigResponseRequiredActionNone:
		return true
	case PutConfigResponseRequiredActionReload:
		return true
	case PutConfigResponseRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for RestoreBackupResponseRequiredAction.
const (
	RestoreBackupResponseRequiredActionRestart RestoreBackupResponseRequiredAction = "restart"
)

// Valid indicates whether the value is a known member of the RestoreBackupResponseRequiredAction enum.
func (e RestoreBackupResponseRequiredAction) Valid() bool {
	switch e {
	case RestoreBackupResponseRequiredActionRestart:
		return true
	default:
		return false
	}
}

// Defines values for ServiceActionResponseAction.
const (
	ServiceActionResponseActionReload  ServiceActionResponseAction = "reload"
	ServiceActionResponseActionRestart ServiceActionResponseAction = "restart"
	ServiceActionResponseActionStart   ServiceActionResponseAction = "start"
	ServiceActionResponseActionStop    ServiceActionResponseAction = "stop"
)

// Valid indicates whether the value is a known member of the ServiceActionResponseAction enum.
func (e ServiceActionResponseAction) Valid() bool {
	switch e {
	case ServiceActionResponseActionReload:
		return true
	case ServiceActionResponseActionRestart:
		return true
	case ServiceActionResponseActionStart:
		return true
	case ServiceActionResponseActionStop:
		return true
	default:
		return false
	}
}

// Defines values for TargetInfoInterfaceState.
const (
	TargetInfoInterfaceStateDown    TargetInfoInterfaceState = "down"
	TargetInfoInterfaceStateUnknown TargetInfoInterfaceState = "unknown"
	TargetInfoInterfaceStateUp      TargetInfoInterfaceState = "up"
)

// Valid indicates whether the value is a known member of the TargetInfoInterfaceState enum.
func (e TargetInfoInterfaceState) Valid() bool {
	switch e {
	case TargetInfoInterfaceStateDown:
		return true
	case TargetInfoInterfaceStateUnknown:
		return true
	case TargetInfoInterfaceStateUp:
		return true
	default:
		return false
	}
}

// Defines values for TargetInfoSources.
const (
	TargetInfoSourcesCidr        TargetInfoSources = "cidr"
	TargetInfoSourcesDomain      TargetInfoSources = "domain"
	TargetInfoSourcesPolicyOrder TargetInfoSources = "policyOrder"
)

// Valid indicates whether the value is a known member of the TargetInfoSources enum.
func (e TargetInfoSources) Valid() bool {
	switch e {
	case TargetInfoSourcesCidr:
		return true
	case TargetInfoSourcesDomain:
		return true
	case TargetInfoSourcesPolicyOrder:
		return true
	default:
		return false
	}
}

// Defines values for TargetInfoType.
const (
	TargetInfoTypeInterface TargetInfoType = "interface"
	TargetInfoTypePolicy    TargetInfoType = "policy"
	TargetInfoTypeUnknown   TargetInfoType = "unknown"
)

// Valid indicates whether the value is a known member of the TargetInfoType enum.
func (e TargetInfoType) Valid() bool {
	switch e {
	case TargetInfoTypeInterface:
		return true
	case TargetInfoTypePolicy:
		return true
	case TargetInfoTypeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ValidationIssueSeverity.
const (
	Error   ValidationIssueSeverity = "error"
	Warning ValidationIssueSeverity = "warning"
)

// Valid indicates whether the value is a known member of the ValidationIssueSeverity enum.
func (e ValidationIssueSeverity) Valid() bool {
	switch e {
	case Error:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for ConfigName.
const (
	ConfigNameCidr    ConfigName = "cidr"
	ConfigNameDomains ConfigName = "domains"
	ConfigNameHrneo   ConfigName = "hrneo"
)

// Valid indicates whether the value is a known member of the ConfigName enum.
func (e ConfigName) Valid() bool {
	switch e {
	case ConfigNameCidr:
		return true
	case ConfigNameDomains:
		return true
	case ConfigNameHrneo:
		return true
	default:
		return false
	}
}

// Defines values for ServiceAction.
const (
	ServiceActionReload  ServiceAction = "reload"
	ServiceActionRestart ServiceAction = "restart"
	ServiceActionStart   ServiceAction = "start"
	ServiceActionStop    ServiceAction = "stop"
)

// Valid indicates whether the value is a known member of the ServiceAction enum.
func (e ServiceAction) Valid() bool {
	switch e {
	case ServiceActionReload:
		return true
	case ServiceActionRestart:
		return true
	case ServiceActionStart:
		return true
	case ServiceActionStop:
		return true
	default:
		return false
	}
}

// Defines values for DeleteCidrTargetRuleParamsKind.
const (
	DeleteCidrTargetRuleParamsKindCidr  DeleteCidrTargetRuleParamsKind = "cidr"
	DeleteCidrTargetRuleParamsKindGeoip DeleteCidrTargetRuleParamsKind = "geoip"
)

// Valid indicates whether the value is a known member of the DeleteCidrTargetRuleParamsKind enum.
func (e DeleteCidrTargetRuleParamsKind) Valid() bool {
	switch e {
	case DeleteCidrTargetRuleParamsKindCidr:
		return true
	case DeleteCidrTargetRuleParamsKindGeoip:
		return true
	default:
		return false
	}
}

// Defines values for DeleteDomainTargetRuleParamsKind.
const (
	Domain  DeleteDomainTargetRuleParamsKind = "domain"
	Geosite DeleteDomainTargetRuleParamsKind = "geosite"
)

// Valid indicates whether the value is a known member of the DeleteDomainTargetRuleParamsKind enum.
func (e DeleteDomainTargetRuleParamsKind) Valid() bool {
	switch e {
	case Domain:
		return true
	case Geosite:
		return true
	default:
		return false
	}
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action   string    `json:"action"`
	BackupId *string   `json:"backupId,omitempty"`
	Error    *string   `json:"error,omitempty"`
	Ok       bool      `json:"ok"`
	Remote   *string   `json:"remote,omitempty"`
	Target   *string   `json:"target,omitempty"`
	Time     time.Time `json:"time"`
}

// AuditEventsResponse defines model for AuditEventsResponse.
type AuditEventsResponse struct {
	Events []AuditEvent `json:"events"`
	Path   string       `json:"path"`
}

// BackupInfo defines model for BackupInfo.
type BackupInfo struct {
	Created time.Time `json:"created"`
	Files   []string  `json:"files"`
	Id      string    `json:"id"`
}

// CIDRBlock defines model for CIDRBlock.
type CIDRBlock struct {
	Comment *string  `json:"comment,omitempty"`
	Enabled bool     `json:"enabled"`
	Entries []string `json:"entries"`
	Geoip   []string `json:"geoip"`
	Target  string   `json:"target"`
}

// CIDRConfig defines model for CIDRConfig.
type CIDRConfig struct {
	Blocks []CIDRBlock `json:"blocks"`
}

// CIDRConfigResponse defines model for CIDRConfigResponse.
type CIDRConfigResponse struct {
	Config CIDRConfig `json:"config"`
	Path   string     `json:"path"`
}

// CIDRRulePatchRequest defines model for CIDRRulePatchRequest.
type CIDRRulePatchRequest struct {
	Apply *bool                    `json:"apply,omitempty"`
	Kind  CIDRRulePatchRequestKind `json:"kind"`
	Value string                   `json:"value"`
}

// CIDRRulePatchRequestKind defines model for CIDRRulePatchRequest.Kind.
type CIDRRulePatchRequestKind string

// CompatibilityCheck defines model for CompatibilityCheck.
type CompatibilityCheck struct {
	Code      string                      `json:"code"`
	Component CompatibilityCheckComponent `json:"component"`
	Message   string                      `json:"message"`
	Path      *string                     `json:"path,omitempty"`
	Severity  CompatibilityCheckSeverity  `json:"severity"`
	Target    *string                     `json:"target,omitempty"`
}

// CompatibilityCheckComponent defines model for CompatibilityCheck.Component.
type CompatibilityCheckComponent string

// CompatibilityCheckSeverity defines model for CompatibilityCheck.Severity.
type CompatibilityCheckSeverity string

// CompatibilityReport defines model for CompatibilityReport.
type CompatibilityReport struct {
	Checks                []CompatibilityCheck `json:"checks"`
	Ok                    bool                 `json:"ok"`
	SupportedHrneoVersion string               `json:"supportedHrneoVersion"`
}

// ConfigFileResponse defines model for ConfigFileResponse.
type ConfigFileResponse struct {
	Content string                 `json:"content"`
	Exists  bool                   `json:"exists"`
	Name    ConfigFileResponseName `json:"name"`

	// Path Destination inside the geofile directory next to hrneo.conf.
	Path           string                            `json:"path"`
	RequiredAction *ConfigFileResponseRequiredAction `json:"requiredAction,omitempty"`
}

// ConfigFileResponseName defines model for ConfigFileResponse.Name.
type ConfigFileResponseName string

// ConfigFileResponseRequiredAction defines model for ConfigFileResponse.RequiredAction.
type ConfigFileResponseRequiredAction string

// DoctorCheck defines model for DoctorCheck.
type DoctorCheck struct {
	Code      string              `json:"code"`
	Component string              `json:"component"`
	Detail    *string             `json:"detail,omitempty"`
	Message   string              `json:"message"`
	Severity  DoctorCheckSeverity `json:"severity"`
}

// DoctorCheckSeverity defines model for DoctorCheck.Severity.
type DoctorCheckSeverity string

// DoctorReport defines model for DoctorReport.
type DoctorReport struct {
	Checks []DoctorCheck `json:"checks"`
	Ok     bool          `json:"ok"`
}

// DomainConfig defines model for DomainConfig.
type DomainConfig struct {
	Targets []DomainTarget `json:"targets"`
}

// DomainConfigResponse defines model for DomainConfigResponse.
type DomainConfigResponse struct {
	Config DomainConfig `json:"config"`
	Path   string       `json:"path"`
}

// DomainDiagnosticCandidate defines model for DomainDiagnosticCandidate.
type DomainDiagnosticCandidate struct {
	MatchType   DomainDiagnosticCandidateMatchType `json:"matchType"`
	Priority    int                                `json:"priority"`
	Rule        string                             `json:"rule"`
	Specificity int                                `json:"specificity"`
	Target      string                             `json:"target"`
}

// DomainDiagnosticCandidateMatchType defines model for DomainDiagnosticCandidate.MatchType.
type DomainDiagnosticCandidateMatchType string

// DomainDiagnosticRequest defines model for DomainDiagnosticRequest.
type DomainDiagnosticRequest struct {
	Domain string `json:"domain"`
}

// DomainDiagnosticResponse defines model for DomainDiagnosticResponse.
type DomainDiagnosticResponse struct {
	Candidates    []DomainDiagnosticCandidate        `json:"candidates"`
	Domain        string                             `json:"domain"`
	MatchType     *DomainDiagnosticResponseMatchType `json:"matchType,omitempty"`
	Matched       bool                               `json:"matched"`
	MatchedDomain *string                            `json:"matchedDomain,omitempty"`
	Notes         []string                           `json:"notes"`
	Target        *string                            `json:"target,omitempty"`
	TargetOrder   []string                           `json:"targetOrder"`
}

// DomainDiagnosticResponseMatchType defines model for DomainDiagnosticResponse.MatchType.
type DomainDiagnosticResponseMatchType string

// DomainRulePatchRequest defines model for DomainRulePatchRequest.
type DomainRulePatchRequest struct {
	Apply *bool                      `json:"apply,omitempty"`
	Kind  DomainRulePatchRequestKind `json:"kind"`
	Value string                     `json:"value"`
}

// DomainRulePatchRequestKind defines model for DomainRulePatchRequest.Kind.
type DomainRulePatchRequestKind string

// DomainTarget defines model for DomainTarget.
type DomainTarget struct {
	Comment *string           `json:"comment,omitempty"`
	Domains []string          `json:"domains"`
	Enabled bool              `json:"enabled"`
	Geosite []string          `json:"geosite"`
	Name    string            `json:"name"`
	Type    *DomainTargetType `json:"type,omitempty"`
}

// DomainTargetType defines model for DomainTarget.Type.
type DomainTargetType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GenerateDefaultHRNeoConfigRequest defines model for GenerateDefaultHRNeoConfigRequest.
type GenerateDefaultHRNeoConfigRequest struct {
	Apply *bool `json:"apply,omitempty"`
}

// GeoDataDownloadRequest defines model for GeoDataDownloadRequest.
type GeoDataDownloadRequest struct {
	AddToConfig *bool       `json:"addToConfig,omitempty"`
	Kind        GeoDataKind `json:"kind"`

	// Path Destination inside the geofile directory next to hrneo.conf.
	Path   string  `json:"path"`
	Sha256 *string `json:"sha256,omitempty"`

	// Url HTTP(S) URL resolving to public IP addresses.
	Url string `json:"url"`
}

// GeoDataFileInfo defines model for GeoDataFileInfo.
type GeoDataFileInfo struct {
	Configured bool        `json:"configured"`
	Exists     bool        `json:"exists"`
	Kind       GeoDataKind `json:"kind"`
	Modified   *time.Time  `json:"modified,omitempty"`
	Path       string      `json:"path"`
	Sha256     *string     `json:"sha256,omitempty"`
	Size       *int64      `json:"size,omitempty"`
}

// GeoDataFileMutationResponse defines model for GeoDataFileMutationResponse.
type GeoDataFileMutationResponse struct {
	ConfigUpdated *bool           `json:"configUpdated,omitempty"`
	File          GeoDataFileInfo `json:"file"`
	Saved         bool            `json:"saved"`
}

// GeoDataFilesResponse defines model for GeoDataFilesResponse.
type GeoDataFilesResponse struct {
	Files []GeoDataFileInfo `json:"files"`
}

// GeoDataKind defines model for GeoDataKind.
type GeoDataKind string

// GeoDataReferencesResponse defines model for GeoDataReferencesResponse.
type GeoDataReferencesResponse struct {
	Geoip   []string `json:"geoip"`
	Geosite []string `json:"geosite"`
}

// GeoDataTagsResponse defines model for GeoDataTagsResponse.
type GeoDataTagsResponse struct {
	Geoip   []string `json:"geoip"`
	Geosite []string `json:"geosite"`
}

// GeoDataUploadRequest defines model for GeoDataUploadRequest.
type GeoDataUploadRequest struct {
	AddToConfig   *bool       `json:"addToConfig,omitempty"`
	ContentBase64 string      `json:"contentBase64"`
	Kind          GeoDataKind `json:"kind"`
	Path          string      `json:"path"`
}

// GroupedCIDRTarget defines model for GroupedCIDRTarget.
type GroupedCIDRTarget struct {
	// Blocks Parsed HR Neo source blocks in file order.
	Blocks []CIDRBlock `json:"blocks"`

	// Enabled True when at least one source block is enabled.
	Enabled bool `json:"enabled"`

	// Entries Unique CIDR entries aggregated from all source blocks.
	Entries []string `json:"entries"`

	// Geoip Unique GeoIP tags aggregated from all source blocks.
	Geoip  []string `json:"geoip"`
	Target string   `json:"target"`
}

// GroupedCIDRViewResponse defines model for GroupedCIDRViewResponse.
type GroupedCIDRViewResponse struct {
	Path    string              `json:"path"`
	Targets []GroupedCIDRTarget `json:"targets"`
}

// GroupedDomainTarget defines model for GroupedDomainTarget.
type GroupedDomainTarget struct {
	// Domains Unique domains aggregated from all source groups.
	Domains []string `json:"domains"`

	// Enabled True when at least one source group is enabled.
	Enabled bool `json:"enabled"`

	// Geosite Unique GeoSite tags aggregated from all source groups.
	Geosite []string `json:"geosite"`

	// Groups Parsed HR Neo source groups in file order.
	Groups []DomainTarget `json:"groups"`
	Name   string         `json:"name"`
}

// GroupedDomainViewResponse defines model for GroupedDomainViewResponse.
type GroupedDomainViewResponse struct {
	Path    string                `json:"path"`
	Targets []GroupedDomainTarget `json:"targets"`
}

// HRNeoConfig defines model for HRNeoConfig.
type HRNeoConfig struct {
	CIDR                 *bool           `json:"CIDR,omitempty"`
	CIDRfile             *string         `json:"CIDRfile,omitempty"`
	ConntrackFlush       *bool           `json:"ConntrackFlush,omitempty"`
	DirectRouteEnabled   *bool           `json:"DirectRouteEnabled,omitempty"`
	GeoIPFile            *[]string       `json:"GeoIPFile,omitempty"`
	GeoSiteFile          *[]string       `json:"GeoSiteFile,omitempty"`
	GlobalRouting        *bool           `json:"GlobalRouting,omitempty"`
	InterfaceFwMarkStart *int            `json:"InterfaceFwMarkStart,omitempty"`
	InterfaceTableStart  *int            `json:"InterfaceTableStart,omitempty"`
	IpsetEnableTimeout   *bool           `json:"IpsetEnableTimeout,omitempty"`
	IpsetMaxElem         *int            `json:"IpsetMaxElem,omitempty"`
	IpsetTimeout         *int            `json:"IpsetTimeout,omitempty"`
	PolicyOrder          *[]string       `json:"PolicyOrder,omitempty"`
	AutoStart            *bool           `json:"autoStart,omitempty"`
	ClearIPSet           *bool           `json:"clearIPSet,omitempty"`
	L7CaptureEnabled     *bool           `json:"l7CaptureEnabled,omitempty"`
	L7ConnbytesMax       *int            `json:"l7ConnbytesMax,omitempty"`
	L7EnableHTTP         *bool           `json:"l7EnableHTTP,omitempty"`
	L7EnableTLS          *bool           `json:"l7EnableTLS,omitempty"`
	L7QueueNum           *int            `json:"l7QueueNum,omitempty"`
	L7TcpReasmEnabled    *bool           `json:"l7TcpReasmEnabled,omitempty"`
	L7TcpReasmMaxEntries *int            `json:"l7TcpReasmMaxEntries,omitempty"`
	L7TcpReasmTtlSec     *int            `json:"l7TcpReasmTtlSec,omitempty"`
	L7WanInterface       *string         `json:"l7WanInterface,omitempty"`
	Log                  *HRNeoConfigLog `json:"log,omitempty"`
	Logfile              *string         `json:"logfile,omitempty"`
	WatchlistPath        *string         `json:"watchlistPath,omitempty"`
}

// HRNeoConfigLog defines model for HRNeoConfig.Log.
type HRNeoConfigLog string

// HRNeoConfigResponse defines model for HRNeoConfigResponse.
type HRNeoConfigResponse struct {
	Config  HRNeoConfig        `json:"config"`
	Path    string             `json:"path"`
	Unknown *map[string]string `json:"unknown,omitempty"`
}

// HRNeoDefaultConfigResponse defines model for HRNeoDefaultConfigResponse.
type HRNeoDefaultConfigResponse struct {
	Config         HRNeoConfig                              `json:"config"`
	Content        string                                   `json:"content"`
	RequiredAction HRNeoDefaultConfigResponseRequiredAction `json:"requiredAction"`
}

// HRNeoDefaultConfigResponseRequiredAction defines model for HRNeoDefaultConfigResponse.RequiredAction.
type HRNeoDefaultConfigResponseRequiredAction string

// HRNeoParamMetadata defines model for HRNeoParamMetadata.
type HRNeoParamMetadata struct {
	CliFlag        string                           `json:"cliFlag"`
	DefaultValue   string                           `json:"defaultValue"`
	Description    string                           `json:"description"`
	Name           string                           `json:"name"`
	Repeatable     bool                             `json:"repeatable"`
	RequiredAction HRNeoParamMetadataRequiredAction `json:"requiredAction"`
	ValueType      HRNeoParamMetadataValueType      `json:"valueType"`
}

// HRNeoParamMetadataRequiredAction defines model for HRNeoParamMetadata.RequiredAction.
type HRNeoParamMetadataRequiredAction string

// HRNeoParamMetadataValueType defines model for HRNeoParamMetadata.ValueType.
type HRNeoParamMetadataValueType string

// HRNeoParamMetadataResponse defines model for HRNeoParamMetadataResponse.
type HRNeoParamMetadataResponse struct {
	Params                []HRNeoParamMetadata `json:"params"`
	SupportedHrneoVersion string               `json:"supportedHrneoVersion"`
}

// HRNeoStatus defines model for HRNeoStatus.
type HRNeoStatus struct {
	Installed bool    `json:"installed"`
	Pid       *int    `json:"pid,omitempty"`
	Running   bool    `json:"running"`
	UptimeSec *int64  `json:"uptimeSec,omitempty"`
	Version   *string `json:"version,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Ok      bool                  `json:"ok"`
	Service HealthResponseService `json:"service"`
}

// HealthResponseService defines model for HealthResponse.Service.
type HealthResponseService string

// IPDiagnosticCandidate defines model for IPDiagnosticCandidate.
type IPDiagnosticCandidate struct {
	Prefix     string `json:"prefix"`
	PrefixBits int    `json:"prefixBits"`
	Priority   int    `json:"priority"`
	Target     string `json:"target"`
}

// IPDiagnosticGeoIPMatch defines model for IPDiagnosticGeoIPMatch.
type IPDiagnosticGeoIPMatch struct {
	Prefix     string `json:"prefix"`
	PrefixBits int    `json:"prefixBits"`
	Priority   int    `json:"priority"`
	Tag        string `json:"tag"`
	Target     string `json:"target"`
}

// IPDiagnosticIPSetMembership defines model for IPDiagnosticIPSetMembership.
type IPDiagnosticIPSetMembership struct {
	Exists        bool     `json:"exists"`
	FirewallRules []string `json:"firewallRules"`
	Member        bool     `json:"member"`
	PolicyMark    *string  `json:"policyMark,omitempty"`
	Priority      int      `json:"priority"`
	SetName       string   `json:"setName"`
	Target        string   `json:"target"`
}

// IPDiagnosticRequest defines model for IPDiagnosticRequest.
type IPDiagnosticRequest struct {
	Ip string `json:"ip"`
}

// IPDiagnosticResponse defines model for IPDiagnosticResponse.
type IPDiagnosticResponse struct {
	Candidates   []IPDiagnosticCandidate     `json:"candidates"`
	GeoipMatches []IPDiagnosticGeoIPMatch    `json:"geoipMatches"`
	Ip           string                      `json:"ip"`
	Matched      bool                        `json:"matched"`
	Notes        []string                    `json:"notes"`
	Prefix       *string                     `json:"prefix,omitempty"`
	Runtime      IPDiagnosticRuntimeEvidence `json:"runtime"`
	Target       *string                     `json:"target,omitempty"`
	TargetOrder  []string                    `json:"targetOrder"`
}

// IPDiagnosticRuntimeEvidence defines model for IPDiagnosticRuntimeEvidence.
type IPDiagnosticRuntimeEvidence struct {
	Errors               []string                          `json:"errors"`
	Family               IPDiagnosticRuntimeEvidenceFamily `json:"family"`
	FirewallAvailable    bool                              `json:"firewallAvailable"`
	IpsetAvailable       bool                              `json:"ipsetAvailable"`
	Matched              bool                              `json:"matched"`
	Memberships          []IPDiagnosticIPSetMembership     `json:"memberships"`
	PolicyMark           *string                           `json:"policyMark,omitempty"`
	PolicyMarksAvailable bool                              `json:"policyMarksAvailable"`
	SetName              *string                           `json:"setName,omitempty"`
	Target               *string                           `json:"target,omitempty"`
}

// IPDiagnosticRuntimeEvidenceFamily defines model for IPDiagnosticRuntimeEvidence.Family.
type IPDiagnosticRuntimeEvidenceFamily string

// ImportCSVApplyResponse defines model for ImportCSVApplyResponse.
type ImportCSVApplyResponse struct {
	Applied        bool                                 `json:"applied"`
	ApplyOutput    *string                              `json:"applyOutput,omitempty"`
	Backup         BackupInfo                           `json:"backup"`
	Preview        ImportCSVPreviewResponse             `json:"preview"`
	RequiredAction ImportCSVApplyResponseRequiredAction `json:"requiredAction"`
	Saved          bool                                 `json:"saved"`
}

// ImportCSVApplyResponseRequiredAction defines model for ImportCSVApplyResponse.RequiredAction.
type ImportCSVApplyResponseRequiredAction string

// ImportCSVPreviewResponse defines model for ImportCSVPreviewResponse.
type ImportCSVPreviewResponse struct {
	Cidr             CIDRConfig         `json:"cidr"`
	CidrValidation   ValidationResponse `json:"cidrValidation"`
	DomainValidation ValidationResponse `json:"domainValidation"`
	Domains          DomainConfig       `json:"domains"`
}

// ImportCSVRequest defines model for ImportCSVRequest.
type ImportCSVRequest struct {
	Apply   *bool  `json:"apply,omitempty"`
	Content string `json:"content"`
}

// ImportTextRequest defines model for ImportTextRequest.
type ImportTextRequest struct {
	Apply   *bool                    `json:"apply,omitempty"`
	Content string                   `json:"content"`
	Enabled *bool                    `json:"enabled,omitempty"`
	Section ImportTextRequestSection `json:"section"`
	Target  string                   `json:"target"`
}

// ImportTextRequestSection defines model for ImportTextRequest.Section.
type ImportTextRequestSection string

// InterfaceInfo defines model for InterfaceInfo.
type InterfaceInfo struct {
	Addresses *[]string          `json:"addresses,omitempty"`
	Name      string             `json:"name"`
	State     InterfaceInfoState `json:"state"`
}

// InterfaceInfoState defines model for InterfaceInfo.State.
type InterfaceInfoState string

// InterfacesResponse defines model for InterfacesResponse.
type InterfacesResponse struct {
	Interfaces []InterfaceInfo `json:"interfaces"`
}

// LogsResponse defines model for LogsResponse.
type LogsResponse struct {
	Lines []string `json:"lines"`
	Path  string   `json:"path"`
}

// OverviewResponse defines model for OverviewResponse.
type OverviewResponse struct {
	CidrRuleCount   int            `json:"cidrRuleCount"`
	DomainRuleCount int            `json:"domainRuleCount"`
	ErrorCount      int            `json:"errorCount"`
	Ok              bool           `json:"ok"`
	Status          StatusResponse `json:"status"`
	TargetCount     int            `json:"targetCount"`
	WarningCount    int            `json:"warningCount"`
}

// PoliciesResponse defines model for PoliciesResponse.
type PoliciesResponse struct {
	Policies []PolicyInfo `json:"policies"`
}

// PolicyInfo defines model for PolicyInfo.
type PolicyInfo struct {
	Mark *string `json:"mark,omitempty"`
	Name string  `json:"name"`
}

// PolicyMutationRequest defines model for PolicyMutationRequest.
type PolicyMutationRequest struct {
	Name string `json:"name"`
	Save *bool  `json:"save,omitempty"`
}

// PolicyMutationResponse defines model for PolicyMutationResponse.
type PolicyMutationResponse struct {
	Command string  `json:"command"`
	Ok      bool    `json:"ok"`
	Output  *string `json:"output,omitempty"`
	Saved   bool    `json:"saved"`
}

// PutCIDRConfigRequest defines model for PutCIDRConfigRequest.
type PutCIDRConfigRequest struct {
	Apply  *bool      `json:"apply,omitempty"`
	Config CIDRConfig `json:"config"`
}

// PutConfigRequest defines model for PutConfigRequest.
type PutConfigRequest struct {
	Apply   *bool  `json:"apply,omitempty"`
	Content string `json:"content"`
}

// PutConfigResponse defines model for PutConfigResponse.
type PutConfigResponse struct {
	Applied        bool                            `json:"applied"`
	ApplyOutput    *string                         `json:"applyOutput,omitempty"`
	Backup         BackupInfo                      `json:"backup"`
	RequiredAction PutConfigResponseRequiredAction `json:"requiredAction"`
	Saved          bool                            `json:"saved"`
}

// PutConfigResponseRequiredAction defines model for PutConfigResponse.RequiredAction.
type PutConfigResponseRequiredAction string

// PutDomainConfigRequest defines model for PutDomainConfigRequest.
type PutDomainConfigRequest struct {
	Apply  *bool        `json:"apply,omitempty"`
	Config DomainConfig `json:"config"`
}

// PutHRNeoConfigRequest defines model for PutHRNeoConfigRequest.
type PutHRNeoConfigRequest struct {
	Apply  *bool       `json:"apply,omitempty"`
	Config HRNeoConfig `json:"config"`
}

// PutTargetOrderRequest defines model for PutTargetOrderRequest.
type PutTargetOrderRequest struct {
	Apply *bool    `json:"apply,omitempty"`
	Order []string `json:"order"`
}

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	Apply *bool  `json:"apply,omitempty"`
	Id    string `json:"id"`
}

// RestoreBackupResponse defines model for RestoreBackupResponse.
type RestoreBackupResponse struct {
	Applied        bool                                `json:"applied"`
	ApplyOutput    *string                             `json:"applyOutput,omitempty"`
	RequiredAction RestoreBackupResponseRequiredAction `json:"requiredAction"`
	Restored       []string                            `json:"restored"`
	SafetyBackup   BackupInfo                          `json:"safetyBackup"`
}

// RestoreBackupResponseRequiredAction defines model for RestoreBackupResponse.RequiredAction.
type RestoreBackupResponseRequiredAction string

// RuntimeDirectRoutesResponse defines model for RuntimeDirectRoutesResponse.
type RuntimeDirectRoutesResponse struct {
	Interfaces []InterfaceInfo `json:"interfaces"`
	Ipv4Error  *string         `json:"ipv4Error,omitempty"`
	Ipv4Rules  []string        `json:"ipv4Rules"`
	Ipv6Error  *string         `json:"ipv6Error,omitempty"`
	Ipv6Rules  []string        `json:"ipv6Rules"`
}

// RuntimeFirewallResponse defines model for RuntimeFirewallResponse.
type RuntimeFirewallResponse struct {
	Ipv4Available bool     `json:"ipv4Available"`
	Ipv4Error     *string  `json:"ipv4Error,omitempty"`
	Ipv4Rules     []string `json:"ipv4Rules"`
	Ipv6Available bool     `json:"ipv6Available"`
	Ipv6Error     *string  `json:"ipv6Error,omitempty"`
	Ipv6Rules     []string `json:"ipv6Rules"`
}

// RuntimeIPSetInfo defines model for RuntimeIPSetInfo.
type RuntimeIPSetInfo struct {
	Exists bool   `json:"exists"`
	Name   string `json:"name"`
}

// RuntimeIPSetsResponse defines model for RuntimeIPSetsResponse.
type RuntimeIPSetsResponse struct {
	Available      bool               `json:"available"`
	Error          *string            `json:"error,omitempty"`
	ReferencedSets []RuntimeIPSetInfo `json:"referencedSets"`
	Sets           []string           `json:"sets"`
}

// ServiceActionResponse defines model for ServiceActionResponse.
type ServiceActionResponse struct {
	Action ServiceActionResponseAction `json:"action"`
	Ok     bool                        `json:"ok"`
	Output string                      `json:"output"`
	Status HRNeoStatus                 `json:"status"`
}

// ServiceActionResponseAction defines model for ServiceActionResponse.Action.
type ServiceActionResponseAction string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Hrbridge struct {
		UptimeSec int64  `json:"uptimeSec"`
		Version   string `json:"version"`
	} `json:"hrbridge"`
	Hrneo HRNeoStatus `json:"hrneo"`
	Paths struct {
		AuditLog   string `json:"auditLog"`
		BackupDir  string `json:"backupDir"`
		CidrList   string `json:"cidrList"`
		DomainConf string `json:"domainConf"`
		HrneoConf  string `json:"hrneoConf"`
	} `json:"paths"`
}

// TargetInfo defines model for TargetInfo.
type TargetInfo struct {
	CidrRules      int                       `json:"cidrRules"`
	DomainRules    int                       `json:"domainRules"`
	Enabled        *bool                     `json:"enabled,omitempty"`
	InterfaceState *TargetInfoInterfaceState `json:"interfaceState,omitempty"`
	Name           string                    `json:"name"`
	Sources        []TargetInfoSources       `json:"sources"`
	Type           TargetInfoType            `json:"type"`
}

// TargetInfoInterfaceState defines model for TargetInfo.InterfaceState.
type TargetInfoInterfaceState string

// TargetInfoSources defines model for TargetInfo.Sources.
type TargetInfoSources string

// TargetInfoType defines model for TargetInfo.Type.
type TargetInfoType string

// TargetInventoryResponse defines model for TargetInventoryResponse.
type TargetInventoryResponse struct {
	Order   []string     `json:"order"`
	Targets []TargetInfo `json:"targets"`
}

// TargetOrderResponse defines model for TargetOrderResponse.
type TargetOrderResponse struct {
	Order []string `json:"order"`
}

// TokenRotateResponse defines model for TokenRotateResponse.
type TokenRotateResponse struct {
	Token string `json:"token"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	Code     string                  `json:"code"`
	Message  string                  `json:"message"`
	Path     *string                 `json:"path,omitempty"`
	Severity ValidationIssueSeverity `json:"severity"`
	Target   *string                 `json:"target,omitempty"`
}

// ValidationIssueSeverity defines model for ValidationIssue.Severity.
type ValidationIssueSeverity string

// ValidationResponse defines model for ValidationResponse.
type ValidationResponse struct {
	Issues []ValidationIssue `json:"issues"`
	Ok     bool              `json:"ok"`
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	AgentVersion string   `json:"agentVersion"`
	ApiVersion   string   `json:"apiVersion"`
	Capabilities []string `json:"capabilities"`
}

// ConfigName defines model for ConfigName.
type ConfigName string

// ServiceAction defines model for ServiceAction.
type ServiceAction string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAuditEventsParams defines parameters for GetAuditEvents.
type GetAuditEventsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeleteCidrTargetRuleParams defines parameters for DeleteCidrTargetRule.
type DeleteCidrTargetRuleParams struct {
	Kind  DeleteCidrTargetRuleParamsKind `form:"kind" json:"kind"`
	Value string                         `form:"value" json:"value"`
	Apply *bool                          `form:"apply,omitempty" json:"apply,omitempty"`
}

// DeleteCidrTargetRuleParamsKind defines parameters for DeleteCidrTargetRule.
type DeleteCidrTargetRuleParamsKind string

// DeleteDomainTargetRuleParams defines parameters for DeleteDomainTargetRule.
type DeleteDomainTargetRuleParams struct {
	Kind  DeleteDomainTargetRuleParamsKind `form:"kind" json:"kind"`
	Value string                           `form:"value" json:"value"`
	Apply *bool                            `form:"apply,omitempty" json:"apply,omitempty"`
}

// DeleteDomainTargetRuleParamsKind defines parameters for DeleteDomainTargetRule.
type DeleteDomainTargetRuleParamsKind string

// PutRawConfigTextBody defines parameters for PutRawConfig.
type PutRawConfigTextBody = string

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// PutStructuredCidrConfigJSONRequestBody defines body for PutStructuredCidrConfig for application/json ContentType.
type PutStructuredCidrConfigJSONRequestBody = PutCIDRConfigRequest

// AddCidrTargetRuleJSONRequestBody defines body for AddCidrTargetRule for application/json ContentType.
type AddCidrTargetRuleJSONRequestBody = CIDRRulePatchRequest

// ValidateCidrConfigJSONRequestBody defines body for ValidateCidrConfig for application/json ContentType.
type ValidateCidrConfigJSONRequestBody = PutCIDRConfigRequest

// PutStructuredDomainConfigJSONRequestBody defines body for PutStructuredDomainConfig for application/json ContentType.
type PutStructuredDomainConfigJSONRequestBody = PutDomainConfigRequest

// AddDomainTargetRuleJSONRequestBody defines body for AddDomainTargetRule for application/json ContentType.
type AddDomainTargetRuleJSONRequestBody = DomainRulePatchRequest

// ValidateDomainConfigJSONRequestBody defines body for ValidateDomainConfig for application/json ContentType.
type ValidateDomainConfigJSONRequestBody = PutDomainConfigRequest

// GenerateDefaultHrneoConfigJSONRequestBody defines body for GenerateDefaultHrneoConfig for application/json ContentType.
type GenerateDefaultHrneoConfigJSONRequestBody = GenerateDefaultHRNeoConfigRequest

// PutStructuredHrneoConfigJSONRequestBody defines body for PutStructuredHrneoConfig for application/json ContentType.
type PutStructuredHrneoConfigJSONRequestBody = PutHRNeoConfigRequest

// PutRawConfigJSONRequestBody defines body for PutRawConfig for application/json ContentType.
type PutRawConfigJSONRequestBody = PutConfigRequest

// PutRawConfigTextRequestBody defines body for PutRawConfig for text/plain ContentType.
type PutRawConfigTextRequestBody = PutRawConfigTextBody

// DiagnoseDomainJSONRequestBody defines body for DiagnoseDomain for application/json ContentType.
type DiagnoseDomainJSONRequestBody = DomainDiagnosticRequest

// DiagnoseIpJSONRequestBody defines body for DiagnoseIp for application/json ContentType.
type DiagnoseIpJSONRequestBody = IPDiagnosticRequest

// DownloadGeodataFileJSONRequestBody defines body for DownloadGeodataFile for application/json ContentType.
type DownloadGeodataFileJSONRequestBody = GeoDataDownloadRequest

// UploadGeodataFileJSONRequestBody defines body for UploadGeodataFile for application/json ContentType.
type UploadGeodataFileJSONRequestBody = GeoDataUploadRequest

// ApplyCsvImportJSONRequestBody defines body for ApplyCsvImport for application/json ContentType.
type ApplyCsvImportJSONRequestBody = ImportCSVRequest

// PreviewCsvImportJSONRequestBody defines body for PreviewCsvImport for application/json ContentType.
type PreviewCsvImportJSONRequestBody = ImportCSVRequest

// ApplyTextImportJSONRequestBody defines body for ApplyTextImport for application/json ContentType.
type ApplyTextImportJSONRequestBody = ImportTextRequest

// PreviewTextImportJSONRequestBody defines body for PreviewTextImport for application/json ContentType.
type PreviewTextImportJSONRequestBody = ImportTextRequest

// PutTargetOrderJSONRequestBody defines body for PutTargetOrder for application/json ContentType.
type PutTargetOrderJSONRequestBody = PutTargetOrderRequest

// CreateTargetPolicyJSONRequestBody defines body for CreateTargetPolicy for application/json ContentType.
type CreateTargetPolicyJSONRequestBody = PolicyMutationRequest
